server:
  port: 8086
  error:
    include-stacktrace: never
    path: never

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references : true
  application:
    name: IGRS-PAYMENT-Preeti
  devtools:
    restart:
      enabled: true
  cloud:
    config:
      enabled: false
        
      
      
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
   
   
   #seaching database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/igrspayment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder : TRACE
              
eureka:
  instance:
    prefer-ip-address: false
  client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://Ankush:Neel123@192.168.1.60:8761/eureka       
         
         
resilience4j:
  circuitbreaker:
    instances:
      statusByFileIdAndUserIdLimiter_Data_Payment: 
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
     
     
  retry:
    instances:
      statusByFileIdAndUserIdRetry_Data_Payment:
        max-attempts: 3
        wait-duration: 5s
             
  
  ratelimiter:
    instances:
      statusByFileIdAndUserIdLimiter_Data_Payment:
        timeout-duration: 2s
        limit-refresh-period: 4s
        limit-for-period: 2  
